services:
  api:
    build: .
    env_file: .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    command: sh -c "/app/start.sh"
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  worker:
    build: .
    env_file: .env
    depends_on:
      - db
      - redis
    command: sh -c "/app/start_worker.sh"
    restart: unless-stopped

volumes:
  pgdata:
